spring:
  data:
    redis:
      host: aws_redis_host
      port: 6379
  datasource:
    url: jdbc:mysql://{RDS_MySQL_Endpoint}:{port}/{database}
    username: { username }
    password: { password }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # 서버 실행시 스키마를 자동으로 생성해주지만 서버 종료시 그대로 유지함
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  key: chojuyeon123456789123456789123456789123456789123456789
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 20160