spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: hereredis.ho9d7r.clustercfg.apn2.cache.amazonaws.com
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-herehere.cuhj2gphxrym.ap-northeast-2.rds.amazonaws.com:3306/heredb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 서버 실행시 스키마를 자동으로 생성해주지만 서버 종료시 그대로 유지함
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao, https://here-here.co.kr/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  key: chojuyeon123456789123456789123456789123456789123456789
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 20160